[cluster]
    # 集群节点配置
    [cluster.node]
        # 实例ID，节点集群中唯一。不填写默认自动生成唯一的实例ID
        id = ""
        # 实例名称
        name = "login"
        # 编解码器。可选：json | proto
        codec = "proto"
        # 加密器。不设置，则不对发送给客户端的消息进行加密。可选：rsa
        encryptor = "rsa"
        # 解密器。不设置，则不对客户端发送的消息进行加密。可选：rsa
        decryptor = "rsa"
[transport]
    # GRPC相关配置
    [transport.grpc]
        # GRPC服务器相关配置
        [transport.grpc.server]
            # 服务器监听地址
            addr = ":8662"
            # 秘钥文件
            keyFile = ""
            # 证书文件
            certFile = ""
        # GRPC客户端相关配置
        [transport.grpc.client]
            # 证书文件
            certFile = ""
            # 证书域名
            serverName = ""
    # RPCX相关配置
    [transport.rpcx]
        # RPCX服务器相关配置
        [transport.rpcx.server]
            # 服务器监听地址
            addr = ":8662"
[packet]
    # 字节序，little | big
    endian = "big"
    # 序列号字节长度（字节）
    seqBytesLen = 2
    # 路由字节长度（字节）
    routeBytesLen = 2
[log]
    # 日志输出文件
    file = "./log/due.log"
    # 日志输出级别，可选：debug | info | warn | error | fatal | panic
    level = "debug"
    # 日志输出格式，可选：text | json
    format = "text"
    # 是否输出到终端
    stdout = true
    # 时间格式，标准库时间格式
    timeFormat = "2006/01/02 15:04:05.000000"
    # 堆栈的最低输出级别，可选：debug | info | warn | error | fatal | panic
    stackLevel = "error"
    # 文件最大留存时间，d:天、h:时、m:分、s:秒
    fileMaxAge = "7d"
    # 文件最大尺寸限制，单位（MB）
    fileMaxSize = 100
    # 文件切割方式
    fileCutRule = "day"
    # 是否启用调用文件全路径
    callerFullPath = true
    # 是否启用分级存储
    classifiedStorage = true
    # zap日志组件。以下配置项如果不存在，则会使用log域中的默认配置项；如果均未配置，则会使用系统默认配置
[locate]
    [locate.redis]
        # 客户端连接地址
        addrs = ["127.0.0.1:6379"]
        # 数据库号
        db = 0
        # 用户名
        username = ""
        # 密码
        password = ""
        # 最大重试次数
        maxRetries = 3
        # key前缀
        prefix = "due"
[registry]
    [registry.etcd]
        # 客户端连接地址
        addrs = ["127.0.0.1:2379"]
        # 客户端拨号超时时间（秒）
        dialTimeout = 5
        # 命名空间
        namespace = "services"
        # 超时时间（秒）
        timeout = 3
        # 心跳重试次数
        retryTimes = 3
        # 心跳重试间隔（秒）
        retryInterval = 10
    [registry.consul]
        # 客户端连接地址
        addr = "127.0.0.1:8500"
        # 是否启用健康检查
        healthCheck = true
        # 健康检查时间间隔（秒），仅在启用健康检查后生效
        healthCheckInterval = 10
        # 健康检查超时时间（秒），仅在启用健康检查后生效
        healthCheckTimeout = 5
        # 是否启用心跳检查
        heartbeatCheck = true
        # 心跳检查时间间隔（秒），仅在启用心跳检查后生效
        heartbeatCheckInterval = 10
        # 健康检测失败后自动注销服务时间（秒）
        deregisterCriticalServiceAfter = 30
[crypto]
    [crypto.rsa]
        # RSA加密设置
        [crypto.rsa.encryptor]
            # hash算法，不区分大小写。可选：SHA1 | SHA224 | SHA256 | SHA384 | SHA512
            hash = "SHA256"
            # 填充规则，不区分大小写。可选：NORMAL | OAEP
            padding = "NORMAL"
            # 标签，加解密时必需一致
            label = ""
            # 加密数据块大小，单位字节。由于加密数据长度限制，需要对加密数据进行分块儿加密
            blockSize = 0
            # 公钥，可设置文件路径或公钥串
            publicKey = "./pem/key.pub.pem"
        # RSA解密设置
        [crypto.rsa.decryptor]
            # hash算法，不区分大小写。可选：SHA1 | SHA224 | SHA256 | SHA384 | SHA512
            hash = "SHA256"
            # 填充规则，不区分大小写。可选：NORMAL | OAEP
            padding = "NORMAL"
            # 标签。加解密时必需一致
            label = ""
            # 私钥。可设置文件路径或私钥串
            privateKey = "./pem/key.pem"